/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: ec8ea3d3d77a982a31129a744ac6b1d5)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env {
    RATE_LIMITER: RateLimit;
    VPC_SERVICE: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
